### ISSUE TITLE
Importing google fonts error

### ISSUE THREAD

**Issue by TheMikeyRoss** [jeetiss/react-pdf-repl#15]
Hi 👋,

I'm trying to submit an issue to [IBM Plex Typeface](https://github.com/IBM/plex) and I want to reproduce that issue with the font while used in a pdf but I'm currently having a problem registering and using the font in react-pdf-repl.

In my regular project when I use `@react-pdf/renderer` in localhost and register IBM font everything works fine, this issue seem to only happen in react-pdf-repl

Here's a [link ](https://react-pdf-repl.vercel.app/?gz_code=eJy9lF1PwjAUhu_3K064wgQoSMSIQET8QgMMRYkaQ8p2NppsbGkPOkL2321nwCvhxixp0o-cvOc5p-0rwjiSBBsLYIIJlfR8Ey2z2eY-liy9uIqcVYjmMAVPRiEULiRyh8qx6zGJSxclysK5ZVkBEvQvB0ZhisJfkII2vGsJow-gpNOEwoIobjLm6SBV8RVxEk7FiUKmmJiHcYCJ4kvFJZ8Lh33Wjtn4q957e6SpPe6t7kJsnNL163M_qT8sqvbd49mwMVeN2ufT3HODboXIKxj6tPQPaQd7074OsW73TnAQdAd-dZcZwNvV34RatfpvOMP9OPZ65vYmL-rl_iGZqD94jvPjGU1ndJCnnmN_RrOzgzwnOfKI8vAgTyPH-7otH34_pzueD_3jzU-vSPSFIpRFw-fxUARrDah9AGyNAU-aA7oZSKaX7_2mRxoTk8zlXPT4KiAoHkG7A0XN0tp6WycrtGU8DxStA2xvNhBz1xVL3zzSUtaEm73FQZr-yGghY6bbjbbWhVCgBwdCRdsY9hvUYiazWbfYFgk6lmb_BuVcwQ8&modules=true)to the repl with this issue

**Comment by TheMikeyRoss** [comment]
@zaaakher Can you look into this?

**Comment by zaaakher** [comment]
@TheMikeyRoss the url you used for the src of the font was `http` instead of `https`

I just changed it to `https`. Here's the [link](https://react-pdf-repl.vercel.app/?gz_code=eJy9lF1PwjAUhu_3K064wgQoSMSIQET8QgMMRYkaQ8p2NppsbGkPOkL2321nwCvhxixp0o-cvOc5p-0rwjiSBBsLYIIJlfR8Ey2z2eY-liy9uIqcVYjmMAVPRiEULiRyh8qx6zGJSxclysK5ZVkBEvQvB0ZhisJfkII2vGsJow-gpNOEwoIobjLm6SBV8RVxEk7FiUKmmJiHcYCJ4kvFJZ8Lh33Wjtn4q957e6SpPe6t7kJsnNL163M_qT8sqvbd49mwMVeN2ufT3HODboXIKxj6tPQPaQd7074OsW73TnAQdAd-dZcZwNvV34RatfpvOMP9OPZ65vYmL-rl_iGZqD94jvPjGU1ndJCnnmN_RrOzgzwnOfKI8vAgTyPH-7otH34_pzueD_3jzU-vSPSFIpRFw-fxUARrDah9AGyNAU-aA7oZSKb3y6_yuOD0SHNiktmcix5fBQTFI2h3oKhhWltz62SVtozpgaJ1gO3NBmLuumLpm1dayrpws7c6SNMfGS1k3HS70d66EAr04ECoaBvDfoNazGQ26xbbIkHH0uzf0l_Bgg&modules=true) to the new repl

**Comment by TheMikeyRoss** [comment]
Oops I totally missed that 😅
Awesome! thanks bro 👍
